version: '3.9'

services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: database
    ports:
      - 5432:5432
