[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum.workspace = true
log.workspace = true
tokio.workspace = true

lib-core = { path = "../../lib/lib-core" }
lib-auth = { path = "../../lib/lib-auth" }
lib-data = { path = "../../lib/lib-data" }
lib-logs = { path = "../../lib/lib-logs" }
