[package]
name = "tools"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, features = [
    "runtime-tokio",
    "postgres",
    "derive",
    "macros",
    "migrate",
] }
lib-data = { path = "../../lib/lib-data" }
tokio.workspace = true
